version: 0.0
os: linux
files:
  - source: /
    destination: /Dev/trydjango/src
hooks:
  BeforeInstall:
    - location: scripts/clean_instance.sh
      timeout: 6000
      runas: root
  AfterInstall:
    - location: scripts/migrate.sh
      timeout: 6000
      runas: root
