version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/Dev/trydjango/src
permissions:
  - object: /home/ec2-user/Dev/trydjango/src
    pattern: "**"
    owner: ec2-user
    group: ec2-user
hooks:
  BeforeInstall:
    - location: scripts/clean_instance.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 600
      runas: root
    - location: scripts/migrate.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_application.sh
      timeout: 600
      runas: root
  ApplicationStop:
    - location: scripts/stop_application.sh
      timeout: 600
      runas: root
