version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/Dev/trydjango/src
hooks:
  BeforeInstall:
    - location: scripts/clean_instance.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 600
      runas: ec2-user
    - location: scripts/migrate.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start_application.sh
      timeout: 600
      runas: ec2-user
  ApplicationStop:
    - location: scripts/stop_application.sh
      timeout: 600
      runas: ec2-user
